version: "2"

services:
    consul-server:
        image: consul:1.5.1
        ports:
            - 8080:8080
        command: agent -server -bootstrap-expect=1 -ui -http-port=8080 -client=0.0.0.0 -node consul-server
    consul-client:
        image: consul:1.5.1
        depends_on: 
            - consul-server
        links:
            - consul-server
        command: agent -node=consul-client1 -join=consul-server
