version: "2"

services:
    web1:
        container_name: web1
        image: nginx:1.13.5
        volumes:
            - ./html/web1.html:/usr/share/nginx/html/index.html:ro
    web2:
        container_name: web2
        image: nginx:1.13.5
        volumes:
            - ./html/web2.html:/usr/share/nginx/html/index.html:ro
    proxy:
        container_name: proxy
        depends_on: 
            - web1
            - web2
        links:
            - web1
            - web2
        ports:
            - 8081:80
        image: nginx:1.13.5
        volumes:
            - ./nginx-config:/etc/nginx/conf.d:ro
    consul-server:
        container_name: consul-server
        image: consul:1.5.1
        ports:
            - 8080:8080
        command: agent -server -bootstrap-expect=1 -ui -http-port=8080 -client=0.0.0.0 -node consul-server
    consul-client1:
        container_name: consul-client1
        image: consul:1.5.1
        depends_on: 
            - consul-server
            - web1
            - web2
            - proxy
        links:
            - consul-server
            - web1
        volumes:
            - ./config/web1.json:/consul/config/web1.json
        command: agent -node=consul-client1 -join=consul-server
    consul-client2:
        container_name: consul-client2
        image: consul:1.5.1
        depends_on: 
            - consul-server
            - web2
        links:
            - consul-server
            - web2
        volumes:
            - ./config/web2.json:/consul/config/web2.json
        command: agent -node=consul-client2 -join=consul-server
            
            
